# Based on DeepInv full at 251238b0f082fc42c83ff72708fdb3fa44de268c.
[workspace]
name = "mu-bregman"
authors = ["Thibaut Modrzyk <52449813+Tmodrzyk@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.9"

[activation.env]
PYTHONNOUSERSITE = "1"
MPLCONFIGDIR = "$PIXI_PROJECT_ROOT/.pixi/matplotlib"
DEEPINV_CACHE_DIR = "$PIXI_PROJECT_ROOT/.pixi/deepinv-cache"
CUPY_CACHE_DIR = "$PIXI_PROJECT_ROOT/.pixi/cupy-cache"
CUDA_PATH = "$CONDA_PREFIX/targets/x86_64-linux"

[tasks]
test = "python -m unittest discover -s python/tests -v"
deconvolution-1 = "python python/notebooks/deconvolution-1.py"
deconvolution-2 = "python python/notebooks/deconvolution-2.py"
deconvolution-tv-stability = "python python/notebooks/deconvolution_tv_stability.py"
pet-2d = "python python/notebooks/pet2d.py"
pet-3d = "python python/notebooks/pet3d.py"
non-convexity = "python python/notebooks/non-convexity.py"
pet = "python python/notebooks/pet3d.py"
pet2d = "python python/notebooks/pet2d.py"

[dependencies]
python = "3.12.*"
numpy = "*"
matplotlib-base = "*"
tqdm = "*"
torchmetrics = "*"
einops = "*"
requests = "*"
h5py = "*"
natsort = "*"
datasets = ">=3.5.0"
pandas = "*"
scipy = "*"
nibabel = "*"
rasterio = "*"
pydicom = "*"
kornia = "*"
pywavelets = "*"
numba = ">=0.60.0"
timm = "*"
diffusers = "*"
transformers = "*"
torchkbnufft = "*"
array-api-compat = "*"
sigpy = "*"
parallelproj = ">=1.10.0,<2.0.0"
astra-toolbox = ">=2.2.0,!=2.3.0"
cupy = "*"
cufinufft = ">=2.5.0"
wandb = "*"
mlflow = "*"
cuda-version = "12.9.*"
libparallelproj = { version = ">=1.10,<2", build = "cuda*" }
seaborn = "*"
ipykernel = "*"

[pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu124" }
brainweb = "==1.7.0"
brainweb-dl = ">=0.4.6"
zea = ">=0.1.0"
deepinv = { git = "https://github.com/deepinv/deepinv.git", rev = "251238b0f082fc42c83ff72708fdb3fa44de268c", extras = ["doc", "test", "dataset", "denoisers", "physics", "physics-gpu", "training"] }

[environments]
full = { features = [] }
